# Generated by Django 6.0.5 on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("optimizer_ui", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="cost",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
