# Generated by Django 6.0.5 on 2026-05-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer_ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientnutrient',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nutrientconstraint',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='ingredientnutrient',
            constraint=models.UniqueConstraint(fields=('ingredient', 'nutrient'), name='unique_ingredient_nutrient'),
        ),
        migrations.AddConstraint(
            model_name='nutrientconstraint',
            constraint=models.UniqueConstraint(fields=('formula', 'nutrient'), name='unique_formula_nutrient_constraint'),
        ),
    ]
