# Generated by Django 6.0.5 on 2026-06-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer_ui', '0003_company_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
