# Generated by Django 6.0.5 on 2026-06-02 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer_ui', '0004_ingredientmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseIngredientNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('ingredient_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_nutrient_values', to='optimizer_ui.ingredientmaster')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer_ui.nutrient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ingredient_master', 'nutrient'), name='unique_base_ingredient_nutrient')],
            },
        ),
    ]
