# Generated by Django 6.0.5 on 2026-06-03 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer_ui', '0005_baseingredientnutrient'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationIngredientSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=100)),
                ('solution_kg', models.FloatField(blank=True, null=True)),
                ('cost_per_kg', models.FloatField(blank=True, null=True)),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('minquantity', models.FloatField(blank=True, null=True)),
                ('maxquantity', models.FloatField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_snapshots', to='optimizer_ui.optimizationrun')),
            ],
        ),
        migrations.CreateModel(
            name='OptimizationNutrientSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient_name', models.CharField(max_length=100)),
                ('actual_value', models.FloatField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_snapshots', to='optimizer_ui.optimizationrun')),
            ],
        ),
    ]
