# Generated by Django 6.0.5 on 2026-06-03 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer_ui', '0006_optimizationingredientsnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantIngredientNutrientOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('ingredient_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_overlays', to='optimizer_ui.ingredientmaster')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer_ui.nutrient')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_nutrient_overlays', to='optimizer_ui.plant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plant', 'ingredient_master', 'nutrient'), name='unique_plant_ingredient_nutrient_overlay')],
            },
        ),
    ]
