# Generated by Django 6.0.5 on 2026-06-03 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer_ui', '0007_plantingredientnutrientoverlay'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formula_ingredients', to='optimizer_ui.ingredientmaster'),
        ),
    ]
